"""Xoa cot age user

Revision ID: 28011c66187e
Revises: 
Create Date: 2025-12-14 23:40:54.146107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28011c66187e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index(op.f('ServiceName'), table_name='servicetypes')
    op.drop_table('servicetypes')
    op.drop_index(op.f('ix_USER_Email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_USERPREFERENCES_UserID'), table_name='userpreferences')
    op.drop_table('userpreferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpreferences',
    sa.Column('PreferenceID', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('DefaultOutputFolder', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Language', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Theme', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('UpdatedAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('userpreferences_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PreferenceID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_USERPREFERENCES_UserID'), 'userpreferences', ['UserID'], unique=True)
    op.create_table('user',
    sa.Column('UserID', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('PhoneNumber', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('DateOfBirth', mysql.DATETIME(), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ProfilePictureURL', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('MemberSince', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('HashedPassword', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('LastLogin', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('Age', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_USER_Email'), 'user', ['Email'], unique=True)
    op.create_table('servicetypes',
    sa.Column('ServiceTypeID', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ServiceName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ServiceDescription', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('ServiceTypeID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ServiceName'), 'servicetypes', ['ServiceName'], unique=True)
    op.create_table('tasks',
    sa.Column('TaskID', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ServiceTypeID', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('OriginalFileName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('OriginalFileSize', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('OriginalFilePath', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('OutputFileName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('OutputFileSize', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('OutputFilePath', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TaskStatus', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('TaskTime', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('InputFormat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('OutputFormat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CompressionLevel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['ServiceTypeID'], ['servicetypes.ServiceTypeID'], name=op.f('tasks_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('tasks_ibfk_1')),
    sa.PrimaryKeyConstraint('TaskID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
